<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use App\Repository\LinkRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=LinkRepository::class)
 * @ORM\Table(name="link",indexes={@ORM\Index(name="guid_status_idx", columns={"guid", "status"}),
 *     @ORM\Index(name="owner_id_idx", columns={"owner_id"})
 * })
 */
class Link
{
    const STATUS_ACTIVE = 'active';
    const STATUS_DISABLED = 'disabled';
    const STATUS_EXPIRED = 'expired';
    const STATUSES = [
        self::STATUS_ACTIVE,
        self::STATUS_DISABLED,
        self::STATUS_EXPIRED
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("APIGroup")
     */
    private $id;

    /**
     * This column contains values generated by trigger_guid_generation trigger
     * I moved this functional to the DB side to make it work faster
     * @ORM\Column(type="string", length=8)
     * @Groups("APIGroup")
     */
    private $guid;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("APIGroup")
     */
    private $link;

    /**
     * @ORM\Column(type="string", length=10)
     * @Groups("APIGroup")
     */
    private $status;

    /**
     * @ORM\OneToMany(targetEntity=Visit::class, mappedBy="link", orphanRemoval=true)
     */
    private $visits;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="links")
     * @ORM\JoinColumn(nullable=false)
     */
    private $owner;

    /**
     * @var \DateTime $created
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     * @Groups("APIGroup")
     */
    private $created;

    /**
     * @ORM\Column(type="integer")
     * @Groups("APIGroup")
     */
    private $expiration_time;


    public function __construct()
    {
        $this->visits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGuid(): ?string
    {
        return $this->guid;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): self
    {
        $this->link = $link;

        return $this;
    }



    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection|Visit[]
     */
    public function getVisits(): Collection
    {
        return $this->visits;
    }

    public function addVisit(Visit $visit): self
    {
        if (!$this->visits->contains($visit)) {
            $this->visits[] = $visit;
            $visit->setLink($this);
        }

        return $this;
    }

    public function removeVisit(Visit $visit): self
    {
        if ($this->visits->removeElement($visit)) {
            // set the owning side to null (unless already changed)
            if ($visit->getLink() === $this) {
                $visit->setLink(null);
            }
        }

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getExpirationTime(): ?int
    {
        return $this->expiration_time;
    }

    public function setExpirationTime(int $expiration_time): self
    {
        $this->expiration_time = $expiration_time;

        return $this;
    }

}
