controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        - api
        - api/{_locale}
    defaults:
            _locale: en

kernel:
    resource: ../../src/Kernel.php
    type: annotation
